repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Check for files that contain merge conflict strings.
      - id: check-merge-conflict
        stages: [pre-commit, pre-push]
      # Simply check whether files parse as valid python.
      - id: check-ast
        stages: [pre-commit]
      # Remove trailing whitespaces
      - id: trailing-whitespace
        stages: [pre-commit]
      # Add newlines to the end of files
      - id: end-of-file-fixer
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        stages: [pre-commit]

      - id: ruff (isort)
        name: ruff-isort
        entry: ruff check --select I --select F401 --fix
        language: system
        types: [python]
        stages: [pre-commit]

      - id: ruff
        name: ruff check
        entry: ruff check
        language: system
        types: [python]
        stages: [pre-push]

      - id: mypy
        name: mypy check
        entry: mypy --enable-incomplete-feature=Unpack vkbottle
        language: system
        pass_filenames: false
        stages: [pre-push]

      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-push]
